import sql from "../db.js";

const templates = [
  ["otp", "OTP Template", "Authentication", "en_US", ["otp", "expiry_minutes"], "Your MMR OTP is {{otp}}. It expires in {{expiry_minutes}} minutes."],
  ["password_reset", "Password Reset Template", "Authentication", "en_US", ["otp", "expiry_minutes"], "Use {{otp}} to reset your MMR password. It expires in {{expiry_minutes}} minutes."],
  ["registration_success", "Registration Success Template", "Utility", "en_US", ["name"], "Welcome {{name}}. Your MMR registration has been completed successfully."],
  ["order_confirmation", "Order Confirmation Template", "Utility", "en_US", ["booking_serial", "plot_number"], "Your plot booking {{booking_serial}} for plot {{plot_number}} has been submitted."],
  ["order_approved", "Order Approved Template", "Utility", "en_US", ["booking_serial"], "Good news. Your booking {{booking_serial}} has been approved."],
  ["order_rejected", "Order Rejected Template", "Utility", "en_US", ["booking_serial", "reason"], "Your booking {{booking_serial}} was rejected. Reason: {{reason}}."],
  ["emi_reminder", "EMI Reminder Template", "Utility", "en_US", ["installment_no", "amount", "due_date"], "Reminder: EMI {{installment_no}} of INR {{amount}} is due on {{due_date}}."],
  ["emi_due_alert", "EMI Due Alert Template", "Utility", "en_US", ["installment_no", "amount", "due_date"], "Your EMI {{installment_no}} of INR {{amount}} is due today, {{due_date}}."],
  ["payment_received", "Payment Received Template", "Utility", "en_US", ["amount", "reference"], "We received your payment of INR {{amount}}. Reference: {{reference}}."],
  ["welcome_message", "Welcome Message Template", "Utility", "en_US", ["name"], "Welcome to MMR Constructions, {{name}}."],
  ["general_notification", "General Notification Template", "Utility", "en_US", ["message"], "{{message}}"],
];

await sql`
  CREATE TABLE IF NOT EXISTS whatsapp_settings (
    id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    provider_name VARCHAR(40) NOT NULL DEFAULT 'meta_cloud',
    phone_number_id VARCHAR(120),
    whatsapp_business_account_id VARCHAR(120),
    encrypted_access_token TEXT,
    encrypted_api_secret TEXT,
    encrypted_verify_token TEXT,
    webhook_callback_url TEXT,
    api_version VARCHAR(20) NOT NULL DEFAULT 'v20.0',
    default_country_code VARCHAR(5) NOT NULL DEFAULT '91',
    otp_length SMALLINT NOT NULL DEFAULT 6 CHECK (otp_length IN (4, 6)),
    otp_expiry_minutes INTEGER NOT NULL DEFAULT 10 CHECK (otp_expiry_minutes BETWEEN 1 AND 1440),
    resend_limit INTEGER NOT NULL DEFAULT 3 CHECK (resend_limit BETWEEN 0 AND 20),
    max_attempts INTEGER NOT NULL DEFAULT 5 CHECK (max_attempts BETWEEN 1 AND 20),
    queue_max_attempts INTEGER NOT NULL DEFAULT 3 CHECK (queue_max_attempts BETWEEN 1 AND 10),
    created_by_admin_id INTEGER,
    updated_by_admin_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`;

await sql`
  CREATE TABLE IF NOT EXISTS whatsapp_templates (
    template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_key VARCHAR(80) NOT NULL UNIQUE,
    template_name VARCHAR(160) NOT NULL,
    template_category VARCHAR(80) NOT NULL,
    language VARCHAR(20) NOT NULL DEFAULT 'en_US',
    template_variables JSONB NOT NULL DEFAULT '[]'::jsonb,
    template_body TEXT NOT NULL,
    meta_template_name VARCHAR(160),
    status VARCHAR(30) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','Inactive','Pending','Approved','Rejected')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_admin_id INTEGER,
    updated_by_admin_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`;

await sql`
  CREATE TABLE IF NOT EXISTS whatsapp_message_logs (
    message_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_id BIGINT,
    user_id INTEGER,
    mobile_no VARCHAR(20) NOT NULL,
    provider_name VARCHAR(40) NOT NULL DEFAULT 'meta_cloud',
    template_key VARCHAR(80),
    meta_message_id VARCHAR(160),
    message_type VARCHAR(40) NOT NULL DEFAULT 'template',
    request_payload JSONB,
    response_payload JSONB,
    status VARCHAR(30) NOT NULL DEFAULT 'Pending',
    delivery_status VARCHAR(30),
    error_code VARCHAR(80),
    error_message TEXT,
    sent_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    read_at TIMESTAMPTZ,
    failed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`;

await sql`
  CREATE TABLE IF NOT EXISTS whatsapp_webhook_logs (
    webhook_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(80),
    meta_message_id VARCHAR(160),
    payload JSONB NOT NULL,
    processed BOOLEAN NOT NULL DEFAULT FALSE,
    processing_error TEXT,
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`;

await sql`
  CREATE TABLE IF NOT EXISTS otp_master (
    otp_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile_no VARCHAR(20) NOT NULL,
    user_id INTEGER,
    purpose VARCHAR(80) NOT NULL,
    otp_hash TEXT NOT NULL,
    otp_length SMALLINT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    resend_count INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    status VARCHAR(30) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','Verified','Expired','Blocked','Used')),
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`;

await sql`
  CREATE TABLE IF NOT EXISTS otp_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    otp_id BIGINT REFERENCES otp_master(otp_id) ON DELETE SET NULL,
    mobile_no VARCHAR(20) NOT NULL,
    purpose VARCHAR(80) NOT NULL,
    action VARCHAR(40) NOT NULL,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    failure_reason TEXT,
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`;

await sql`
  CREATE TABLE IF NOT EXISTS notification_queue (
    queue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel VARCHAR(30) NOT NULL DEFAULT 'whatsapp',
    provider_name VARCHAR(40) NOT NULL DEFAULT 'meta_cloud',
    template_key VARCHAR(80),
    recipient_mobile VARCHAR(20) NOT NULL,
    user_id INTEGER,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    priority INTEGER NOT NULL DEFAULT 5,
    status VARCHAR(30) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Processing','Sent','Failed')),
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 3,
    scheduled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ,
    last_error TEXT,
    created_by_admin_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`;

await sql`CREATE INDEX IF NOT EXISTS idx_whatsapp_message_logs_status ON whatsapp_message_logs(status, created_at DESC)`;
await sql`CREATE INDEX IF NOT EXISTS idx_whatsapp_message_logs_meta ON whatsapp_message_logs(meta_message_id)`;
await sql`CREATE INDEX IF NOT EXISTS idx_whatsapp_webhook_logs_meta ON whatsapp_webhook_logs(meta_message_id, received_at DESC)`;
await sql`CREATE INDEX IF NOT EXISTS idx_otp_master_mobile_purpose ON otp_master(mobile_no, purpose, status, created_at DESC)`;
await sql`CREATE INDEX IF NOT EXISTS idx_notification_queue_status ON notification_queue(status, scheduled_at, priority)`;

await sql`INSERT INTO whatsapp_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING`;

for (const [key, name, category, language, variables, body] of templates) {
  await sql`
    INSERT INTO whatsapp_templates (template_key, template_name, template_category, language, template_variables, template_body, meta_template_name)
    VALUES (${key}, ${name}, ${category}, ${language}, ${sql.json(variables)}, ${body}, ${key})
    ON CONFLICT (template_key) DO NOTHING`;
}

console.log("WhatsApp integration tables are ready.");
await sql.end();
