import sql from "../db.js";

const currentSlides = [
  {
    title: "Apne Sapno Ka",
    subtitle: "Plot Book Karein",
    description: "Kanpur, Unnao aur Lucknow mein affordable premium plots. Easy EMI, buyback guarantee aur prime location.",
    image_url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80",
    tag_text: "Premium Affordable Plots",
    tag_icon: "fas fa-star",
    button_text: "Explore Plots",
    button_link: "#sites",
    button_icon: "fas fa-map-marked-alt",
    button2_text: "Register Free",
    button2_link: "/register",
    button2_icon: "fas fa-user-plus",
    thumbnail_url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=120&q=70",
    thumbnail_title: "Explore Plots",
    thumbnail_subtitle: "5 Sites",
    stats: [{ num: "5+", lbl: "Active Sites" }, { num: "500+", lbl: "Happy Customers" }, { num: "2019", lbl: "Established" }],
  },
  {
    title: "Buyback",
    subtitle: "Guarantee",
    description: "2 saal mein buyback guarantee. Original price + ₹1,00,000 wapas. Aapka investment secure hai.",
    image_url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1600&q=80",
    tag_text: "100% Secure Investment",
    tag_icon: "fas fa-shield-alt",
    button_text: "Learn More",
    button_link: "/buyback",
    button_icon: "fas fa-shield-alt",
    button2_text: "EMI Calculator",
    button2_link: "#emi",
    button2_icon: "fas fa-calculator",
    thumbnail_url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=120&q=70",
    thumbnail_title: "Buyback Guarantee",
    thumbnail_subtitle: "100% Secure",
    stats: [{ num: "₹1L", lbl: "Extra on Buyback" }, { num: "2 Yr", lbl: "Buyback Window" }, { num: "100%", lbl: "Safe Investment" }],
  },
  {
    title: "12 Saal Tak",
    subtitle: "₹12,000/Mahina Kamayein",
    description: "Associate banein, plot bechein aur 12 saal tak monthly commission paayein.",
    image_url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1600&q=80",
    tag_text: "Associate Commission Program",
    tag_icon: "fas fa-rupee-sign",
    button_text: "Earn With Us",
    button_link: "#earn",
    button_icon: "fas fa-hand-holding-usd",
    button2_text: "Join as Associate",
    button2_link: "/signup?type=Associate",
    button2_icon: "fas fa-user-tie",
    thumbnail_url: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=120&q=70",
    thumbnail_title: "Earn With Us",
    thumbnail_subtitle: "12 Year Income",
    stats: [{ num: "₹600", lbl: "per 100 gaj/month" }, { num: "12 Yr", lbl: "Income Duration" }, { num: "₹3L", lbl: "Target Bonus" }],
  },
  {
    title: "5 Sites —",
    subtitle: "Highway Ke Nazdeek",
    description: "Airport, highway aur railway station se kuch minutes door, paved roads aur 24×7 electricity ke saath.",
    image_url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1600&q=80",
    tag_text: "Prime Highway Locations",
    tag_icon: "fas fa-map-pin",
    button_text: "View All Sites",
    button_link: "#sites",
    button_icon: "fas fa-map",
    button2_text: "Our Facilities",
    button2_link: "#facilities",
    button2_icon: "fas fa-list-check",
    thumbnail_url: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=120&q=70",
    thumbnail_title: "Prime Locations",
    thumbnail_subtitle: "3 Cities",
    stats: [{ num: "5", lbl: "Active Sites" }, { num: "3", lbl: "Cities" }, { num: "50+", lbl: "Nearby Landmarks" }],
  },
  {
    title: "₹51,000 Se",
    subtitle: "Apna Plot Shuru Karein",
    description: "Minimum down payment aur ₹3,000/month EMI se plot book karein. Bank finance bhi available hai.",
    image_url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1600&q=80",
    tag_text: "Affordable Payment Plans",
    tag_icon: "fas fa-money-bill-wave",
    button_text: "Calculate EMI",
    button_link: "#emi",
    button_icon: "fas fa-calculator",
    button2_text: "Book a Plot",
    button2_link: "/register",
    button2_icon: "fas fa-home",
    thumbnail_url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=120&q=70",
    thumbnail_title: "Easy EMI",
    thumbnail_subtitle: "₹51K Down Payment",
    stats: [{ num: "₹51K", lbl: "Min Down Payment" }, { num: "₹3K", lbl: "Monthly EMI" }, { num: "5 Yr", lbl: "Tenure" }],
  },
];

try {
  await sql`
    CREATE TABLE IF NOT EXISTS home_sliders (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      subtitle TEXT,
      description TEXT,
      image_url TEXT NOT NULL,
      image_public_id TEXT,
      button_text TEXT,
      button_link TEXT,
      button_icon TEXT,
      button2_text TEXT,
      button2_link TEXT,
      button2_icon TEXT,
      tag_text TEXT,
      tag_icon TEXT,
      thumbnail_url TEXT,
      thumbnail_title TEXT,
      thumbnail_subtitle TEXT,
      stats_json JSONB NOT NULL DEFAULT '[]'::jsonb,
      show_image BOOLEAN NOT NULL DEFAULT TRUE,
      show_tag BOOLEAN NOT NULL DEFAULT TRUE,
      show_title BOOLEAN NOT NULL DEFAULT TRUE,
      show_subtitle BOOLEAN NOT NULL DEFAULT TRUE,
      show_description BOOLEAN NOT NULL DEFAULT TRUE,
      show_button1 BOOLEAN NOT NULL DEFAULT TRUE,
      show_button2 BOOLEAN NOT NULL DEFAULT TRUE,
      show_stats BOOLEAN NOT NULL DEFAULT TRUE,
      show_thumbnail BOOLEAN NOT NULL DEFAULT TRUE,
      display_order INTEGER NOT NULL DEFAULT 0,
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      created_by_admin_id INTEGER,
      updated_by_admin_id INTEGER,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`;

  const additions = [
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS button_icon TEXT`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS button2_text TEXT`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS button2_link TEXT`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS button2_icon TEXT`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS tag_text TEXT`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS tag_icon TEXT`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS thumbnail_url TEXT`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS thumbnail_title TEXT`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS thumbnail_subtitle TEXT`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS stats_json JSONB NOT NULL DEFAULT '[]'::jsonb`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS show_image BOOLEAN NOT NULL DEFAULT TRUE`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS show_tag BOOLEAN NOT NULL DEFAULT TRUE`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS show_title BOOLEAN NOT NULL DEFAULT TRUE`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS show_subtitle BOOLEAN NOT NULL DEFAULT TRUE`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS show_description BOOLEAN NOT NULL DEFAULT TRUE`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS show_button1 BOOLEAN NOT NULL DEFAULT TRUE`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS show_button2 BOOLEAN NOT NULL DEFAULT TRUE`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS show_stats BOOLEAN NOT NULL DEFAULT TRUE`,
    sql`ALTER TABLE home_sliders ADD COLUMN IF NOT EXISTS show_thumbnail BOOLEAN NOT NULL DEFAULT TRUE`,
  ];
  for (const addition of additions) await addition;

  await sql`
    CREATE INDEX IF NOT EXISTS idx_home_sliders_active_order
    ON home_sliders (display_order ASC, id ASC)
    WHERE is_active = TRUE`;

  const [{ count }] = await sql`SELECT COUNT(*)::int AS count FROM home_sliders`;
  if (count === 0) {
    for (let index = 0; index < currentSlides.length; index++) {
      const slide = currentSlides[index];
      await sql`
        INSERT INTO home_sliders (
          title, subtitle, description, image_url, tag_text, tag_icon,
          button_text, button_link, button_icon, button2_text, button2_link, button2_icon,
          thumbnail_url, thumbnail_title, thumbnail_subtitle, stats_json,
          display_order, is_active
        ) VALUES (
          ${slide.title}, ${slide.subtitle}, ${slide.description}, ${slide.image_url},
          ${slide.tag_text}, ${slide.tag_icon},
          ${slide.button_text}, ${slide.button_link}, ${slide.button_icon},
          ${slide.button2_text}, ${slide.button2_link}, ${slide.button2_icon},
          ${slide.thumbnail_url}, ${slide.thumbnail_title}, ${slide.thumbnail_subtitle},
          ${sql.json(slide.stats)}, ${index + 1}, TRUE
        )`;
    }
  }

  const sliders = await sql`
    SELECT id, title, subtitle, display_order, is_active
    FROM home_sliders
    ORDER BY display_order, id`;
  console.log(JSON.stringify({ success: true, seeded: count === 0, sliders }, null, 2));
} finally {
  await sql.end();
}
